"""
Shared dataclass schemas for the Regulatory Evidence Service.

These typed containers replace raw dicts across all service methods,
giving callers a consistent, documented API.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PrecedentCard:
    """A single regulatory precedent with relevance metadata."""
    id: str
    title: str
    agency: str                     # "FDA" | "EMA"
    year: int
    issue_category: str
    outcome: str
    source: str
    relevance: float                # 0-1
    relevance_tags: List[str] = field(default_factory=list)
    molecule_type: str = ""


@dataclass
class ReviewerQuestion:
    """A predicted reviewer question with probability and impact."""
    id: str
    question: str
    category: str
    probability: float              # 0-1
    impact: str                     # "critical" | "high" | "medium" | "low"
    ich_reference: str = ""
    trigger: str = ""


@dataclass
class AreaScore:
    """Score for one of the 8 CMC readiness evidence areas."""
    area_id: str
    name: str
    score: float                    # 0-1
    weight: float
    status: str                     # "Ready" | "Near-ready" | "In progress" | "Not ready"
    gaps: List[str] = field(default_factory=list)


@dataclass
class ReadinessReport:
    """Aggregate CMC submission readiness assessment."""
    composite: float                # 0-1 weighted composite
    verdict: str
    n_areas: int
    n_ready: int
    n_blockers: int
    blockers: List[str] = field(default_factory=list)
    area_scores: List[AreaScore] = field(default_factory=list)


@dataclass
class FindingClassification:
    """Classification of a regulatory finding against FDA WL taxonomy."""
    primary_category: str           # e.g. "CMC_ANALYTICAL"
    primary_severity: str           # "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"
    n_categories_matched: int
    top_categories: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PredictedQuestion:
    """A predicted reviewer question from comparability analysis.

    Generated by the self-contained reviewer risk engine using local
    templates and evidence registry. No external dependency required.
    """
    id: str
    question: str
    category: str
    attribute_name: str
    probability: float              # 0-1, estimated likelihood reviewer asks this
    severity: str                   # "critical" | "high" | "medium" | "low"
    suggested_response: str
    ich_reference: str = ""
    trigger: str = ""
    template_id: str = ""


@dataclass
class EvidenceGrade:
    """Evidence strength grade for a scientific/regulatory claim."""
    grade: str                      # "strong" | "moderate" | "weak" | "anecdotal"
    probabilities: Dict[str, float] = field(default_factory=dict)
